### ISSUE TITLE
Website giving PR_CONNECT_RESET_ERROR 

### ISSUE THREAD

**Issue by evan-person** [audio-imagination/audio-imagination.github.io#1]
When visiting audio-imagination.github.io, I can't view the webpage because it's giving a PR_CONNECT_RESET_ERROR.

**Comment by nateanl** [comment]
Hi @evan-person, can you try to access https://www.audio-imagination.com/ directly, will that solve the connection issue?

**Comment by evan-person** [comment]
That works great! Please update the link from the NeurIPS submission page as well as the NeurIPS workshop page.
